# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(626, 438)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/logo_App.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"border: 0px solid rgb(0, 0, 0);\n"
"\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:0, y2:0, stop:0.429022 rgba(127, 90, 240, 255), stop:0.957413 rgba(15, 14, 23, 255));\n"
"border-radius:0px;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"    font: 12pt \"Lato\";\n"
"     border-radius: 10px;\n"
"     background-color:      #7f5af0;\n"
"    width:                 24px;\n"
"    height:                 24px;\n"
"    border: 3px solid  #0f0e17;\n"
"    }\n"
"\n"
"\n"
" QPushButton:hover {\n"
"        background-color:#0f0e17;\n"
"        color: #ffffff;\n"
"        border: 3px solid  #7f5af0;\n"
"    }\n"
"\n"
"    QPushButton:disabled {\n"
"        background-color: #0f0e17;\n"
"        color: grey;\n"
"        border: 3px solid  grey;\n"
"    }\n"
"\n"
"QGroupBox{\n"
"background-color: #0f0e17;\n"
"font: 12pt \"Lato\";\n"
"color: white;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.bt_ingresar = QtWidgets.QPushButton(parent=self.frame)
        self.bt_ingresar.setGeometry(QtCore.QRect(429, 324, 161, 41))
        self.bt_ingresar.setStyleSheet("")
        self.bt_ingresar.setObjectName("bt_ingresar")
        self.nombre_usuario = QtWidgets.QLineEdit(parent=self.frame)
        self.nombre_usuario.setGeometry(QtCore.QRect(91, 329, 171, 41))
        self.nombre_usuario.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.nombre_usuario.setStyleSheet("QLineEdit {\n"
"font: 12pt \"Lato\";\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.nombre_usuario.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.nombre_usuario.setText("")
        self.nombre_usuario.setMaxLength(60)
        self.nombre_usuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nombre_usuario.setDragEnabled(False)
        self.nombre_usuario.setReadOnly(False)
        self.nombre_usuario.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.nombre_usuario.setClearButtonEnabled(False)
        self.nombre_usuario.setObjectName("nombre_usuario")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 431, 321))
        self.label_2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(0,0,0,0%);\n"
"border:0px;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Images/logo_App.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(parent=self.frame)
        self.progressBar.setGeometry(QtCore.QRect(30, 390, 571, 21))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgba(0,0,0,0%);\n"
"     border-radius:10px;\n"
"border: 1px solid #000000;\n"
"\n"
"\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0.573864, x2:1, y2:0.568, stop:0.429022 rgba(127, 90, 240, 255), stop:0.957413 rgba(15, 14, 23, 255));\n"
"\n"
"     border-radius:10px;\n"
"\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.Direction.BottomToTop)
        self.progressBar.setObjectName("progressBar")
        self.pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton.setGeometry(QtCore.QRect(560, 10, 40, 40))
        self.pushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"font: 75 20pt \"MS Sans Serif\";\n"
"background-color: rgba(0, 0, 0,0%);\n"
"border:  None;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:0px;\n"
"color: rgb(0, 0, 0);\n"
"border: 2px solid #0f0e17;\n"
"}\n"
"\n"
"")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/x.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(36, 36))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mecanismo de 4 barras"))
        self.bt_ingresar.setText(_translate("MainWindow", "INGRESAR"))
        self.nombre_usuario.setPlaceholderText(_translate("MainWindow", "Ingrese su nombre"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
